// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
//
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });
//
// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });
//
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
//
// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { LocalAuthProvider } from '@/components/auth/LocalAuthProvider'
import { AppHeader } from '@/components/Header'
import { FloatingChatbotWidget } from '@/components/chatbot/ChatbotWidget'
import { LoginPromptBubble } from '@/components/LoginPromptBubble'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Modern Next.js App',
  description: 'A modern Next.js application with shadcn/ui, Tailwind, and Zustand',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <LocalAuthProvider>
          <div className="min-h-screen bg-background font-sans antialiased flex flex-col">
            <AppHeader />
            <main className="flex-1 relative">
              {children}
              <FloatingChatbotWidget
                iframeSrc="https://copilotstudio.microsoft.com/environments/Default-30eecfdf-8e95-4b3c-9c51-fe8aa6c21e05/bots/cr405_financialFaqChat/webchat?__version__=2"
                position="bottom-right"
                theme="brand"
                size='large'
                title="FinReg Assistant"
                subtitle="Ask me about Botswana financial regulations"
              />
              <LoginPromptBubble />
            </main>
          </div>
        </LocalAuthProvider>
      </body>
    </html>
  )
}
